function distance_map=get_lattice(misorientation, lattice_spacing, x_o, y_o, X,Y, fourier_degree)%degree
    distance_map = edge_level_plane(misorientation, lattice_spacing, x_o, y_o, X,Y, fourier_degree)...
    +edge_level_plane(pi/3+misorientation, lattice_spacing, x_o, y_o, X,Y, fourier_degree)...
    +edge_level_plane(2*pi/3+misorientation, lattice_spacing, x_o, y_o, X,Y, fourier_degree);
end