function distance_map=get_lattice(misorientation, lattice_spacing, x_o, y_o, X,Y)%degree
    distance_map = edge_level_plane(misorientation, lattice_spacing, x_o, y_o, X,Y)...
    +edge_level_plane(2*pi/3+misorientation, lattice_spacing, x_o, y_o, X,Y)...
    +edge_level_plane(4*pi/3+misorientation, lattice_spacing, x_o, y_o, X,Y);
end